const selectedPage=()=>window._page||10;window._page=10;
const pagePicker=document.getElementById("pagePicker"),grid=document.getElementById("adGrid"),summarySquares=document.getElementById("summarySquares"),summaryPrice=document.getElementById("summaryPrice"),preview=document.getElementById("advertPreview"),previewPage=document.getElementById("previewPage");
let chosen=new Set();const sold={10:[1,2,3,14,15,26,39,40],7:[5,6,18,30,31],2:[20,21,22,34]};
function rate(p){return p<=5?10:p<=9?5:1.5}
function tier(p){return p<=5?"PREMIUM":p<=9?"SEMI":"STANDARD"}
function renderPages(){pagePicker.innerHTML=Array.from({length:12},(_,i)=>i+1).map(p=>`<button class="${p===selectedPage()?"active":""}" data-p="${p}"><b>PAGE ${p}</b><span>${tier(p)}</span><small>£${rate(p).toFixed(2)} / square</small></button>`).join("");pagePicker.querySelectorAll("button").forEach(b=>b.onclick=()=>{window._page=+b.dataset.p;chosen.clear();renderPages();renderGrid();update()})}
function renderGrid(){const soldHere=new Set(sold[selectedPage()]||[]);grid.innerHTML="";for(let i=0;i<96;i++){const b=document.createElement("button");b.className="grid-square";if(soldHere.has(i))b.classList.add("sold");if(chosen.has(i))b.classList.add("chosen");b.disabled=soldHere.has(i);b.title=b.disabled?"Already sold":"Click to select";b.onclick=()=>{chosen.has(i)?chosen.delete(i):chosen.add(i);renderGrid();update()};grid.appendChild(b)}}
function update(){const n=chosen.size,total=n*rate(selectedPage());summarySquares.textContent=n+" square"+(n===1?"":"s");summaryPrice.textContent="£"+total.toFixed(2);previewPage.textContent=selectedPage();preview.innerHTML=n>=3?`<strong>${esc(document.getElementById("business").value||"Your Business")}</strong><span>${esc(document.getElementById("tagline").value||"Your advert will appear here.")}</span>`:`<strong>Your Business</strong><span>Select at least 3 squares.</span>`}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.getElementById("advertForm").addEventListener("input",update);
document.getElementById("advertForm").addEventListener("submit",e=>{e.preventDefault();if(chosen.size<3){alert("Please select at least 3 squares.");return}const d={page:selectedPage(),squares:[...chosen],price:chosen.size*rate(selectedPage()),business:document.getElementById("business").value,email:document.getElementById("email").value,website:document.getElementById("website").value,phone:document.getElementById("phone").value,tagline:document.getElementById("tagline").value};localStorage.setItem("helloPagesPendingOrder",JSON.stringify(d));location.href="checkout.html"});
renderPages();renderGrid();update();
